### ISSUE TITLE
configure coin microservice

### ISSUE THREAD

**Issue by plopezgit** [plopezgit/Saving#9]
```
server:
  port: 8090

spring:
  application:
    name: msvc-coin
  data:
    mongodb:
      host: localhost
      port: 27017
      database: coins
      auto-index-creation: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
```
